In [1]:
#Day 3

In [83]:
class Count:
    def __init__(self):
        self.num = 0
    def increment(self):
        self.num += 1
        return self.num

In [84]:
c = Count()

In [85]:
c.num

0

In [88]:
c.increment()

2

In [89]:
c.num

2

In [35]:
d = Count()

In [36]:
d.num

0

In [90]:
import os

In [91]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'ARGV',
 'day_2.ipynb',
 'day_3.ipynb',
 'README.md',
 'test.py',
 'Untitled.ipynb']

In [92]:
import os

In [94]:
os.listdir("0621")

['main.py', 'test.py', 'test.txt', '__pycache__']

In [129]:
f = open("0621/test.txt","r") #r:파일 일기 W:파일 쓰기 a:내용 추가하기

In [130]:
text = f.read()

In [131]:
print(text)

Hello World!


In [133]:
f.close()

In [144]:
f = open("0621/test.txt","w")

In [145]:
f.write("My name is")
f.close()

In [146]:
f= open("0621/test.txt","a")

In [147]:
f.write(" Lee Shihwan")
f.close()

In [148]:
f = open("0621/order.txt","r")
data = f.read()
print(data)

id  menu    price
1   pizza   10$
2   chicken 15$
3   hamburger   5$


In [159]:
f = open("0621/order.txt","r")
line = f.readline()
print(line)
line = f.readline()
print(line)

id  menu    price

1   pizza   10$



In [160]:
f = open("0621/order.txt","r")
lines = f.readlines()
print(lines)

['id  menu    price\n', '1   pizza   10$\n', '2   chicken 15$\n', '3   hamburger   5$']


In [161]:
f = open("0621/order.txt","r")
lines = f.readlines()
header = lines[0]
contents = lines[1:]
print(header)
print(contents)

id  menu    price

['1   pizza   10$\n', '2   chicken 15$\n', '3   hamburger   5$']


In [165]:
with open("0621/order.txt","r") as f:
    lines = f.readlines()

lines

['id  menu    price\n',
 '1   pizza   10$\n',
 '2   chicken 15$\n',
 '3   hamburger   5$']

In [172]:
#문자열 관련 함수
a = "Hello World"

len(a)

11

In [174]:
a = "      Hello World      "

a.strip()

'Hello World'

In [175]:
a = "      Hello World      "

a.lstrip()

'Hello World      '

In [176]:
a = "      Hello World      "

a.rstrip()

'      Hello World'

In [177]:
a = "Hello World"

In [179]:
a.split("o")

['Hell', ' W', 'rld']

In [181]:
a.replace("Hello","Hi")

'Hi World'

In [182]:
a.upper()

'HELLO WORLD'

In [184]:
a.lower()

'hello world'

In [185]:
a.startswith("Hello")

True

In [186]:
a.startswith("Hi")

False

In [190]:
a.endswith("d")

True

In [191]:
a.find("o")

4

In [192]:
a.find("z")

-1

In [200]:
f = open("0621/order.txt","r")
data = f.readlines()
print(data[1].split()[1])


pizza


In [223]:
f = open("0621/data.txt","r",encoding='utf-8')
data = f.readlines()
# print(data)

# 평균 계산
# data : 한 줄 한 줄 있는 리스트 
total = 0
for line in data:
    # line : "이름 점수\n"
    # line.split() : ["이름","점수"]
    # line.split()[1] : 점수
    score = line.split()[1]
    if score == "점수":
        continue
    #print(score)
    total += int(score)

#print(total / (len(data)-1))
avg = total / (len(data)-1)
print("평균은",avg,"입니다.")

평균은 79.0 입니다.


In [226]:
import time

In [237]:
# 1970.01.01 00:00
time.time()

1750484695.646184

In [238]:
import datetime

In [239]:
datetime.datetime.now()

datetime.datetime(2025, 6, 21, 14, 46, 6, 255042)

In [240]:
import os

In [241]:
os.name

'nt'

In [242]:
os.getcwd()

'C:\\Users\\admin\\Desktop\\sh\\Edu_python'

In [255]:
os.listdir("0621")

['data.txt', 'main.py', 'order.txt', 'test.py', 'test.txt', '__pycache__']

In [249]:
os.path.exists("0621")

True

In [258]:
os.remove("test.txt")#제거

FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'test.txt'

In [260]:
os.system("echo Hello")

0

In [335]:
import sys
sys.platform

'win32'

In [337]:
import numpy as np

In [338]:
# 1차원 배열
a1 = np.array([1,2,3])

# 2차원 배열
a2 = np.array([[1,2,3],[4,5,6]])

# 3차원 배열
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [340]:
print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [341]:
a1.shape

(3,)

In [342]:
a2.shape

(2, 3)

In [343]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [344]:
a+1

array([2, 3, 4])

In [345]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [346]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [347]:
a=np.array([1,2,3])

In [348]:
np.median(a)

2.0

In [349]:
a = np.array([[1,2,3],[4,5,6]])

In [350]:
np.mean(a,axis=1)

array([2., 5.])

In [351]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [352]:
a = np.array([1, 2, 3, 4, 5])

In [353]:
a[0]

1

In [354]:
a = np.array([[1,2,3],[4,5,6]])

In [355]:
a[0]

array([1, 2, 3])

In [356]:
a[0][0]

1

In [357]:
a[1][1]

5

In [358]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [359]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [360]:
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [361]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [362]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [363]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [364]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [365]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [366]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [367]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [368]:
a = np.array([1, 2, 3, 4, 5, 6])

In [369]:
b, c = np.split(a, [3])

In [370]:
print(b)
print(c)

[1 2 3]
[4 5 6]
